id: A7A09C185
title: CXIII_ยง134
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:34:47.137056
  last_modified_at: 2022-03-01 21:34:47.137060
