id: A7A09C185
title: CIII_ยง30
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:34:46.957399
  last_modified_at: 2022-03-01 21:34:46.957402
