id: A7A09C185
title: CX_ยง101
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:34:47.225117
  last_modified_at: 2022-03-01 21:34:47.225120
