id: A7A09C185
title: CIV_ยง34
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:34:46.991776
  last_modified_at: 2022-03-01 21:34:46.991779
