id: A7A09C185
title: CII_ยง13
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:34:46.963337
  last_modified_at: 2022-03-01 21:34:46.963340
