id: A7A09C185
title: CIII_ยง25
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:34:46.945142
  last_modified_at: 2022-03-01 21:34:46.945149
